development:
  adapter: postgresql
  encoding: unicode
  database: dev_react_todo
  host: 127.0.0.1
  pool: 5
  username: postgres
  password: password

test: &test
  adapter: postgresql
  database: test_react_todo
  encoding: unicode
  host: 127.0.0.1
  pool: 5
  username: postgres
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: prod_react_todo
  host: 127.0.0.1
  pool: 5
  username: postgres
  password: password